testnet = true
access_key = ""
secret_key = ""
category = "linear"
symbols = "BTCUSDT"
depth = 1
is_local_based = true

[strategy]
name = "SmartGridStrategy"

[params]
grid_interval = 0.01
order_qty = 0.001
# Set overall stop-loss percentage
total_sl_percent = -0.1
# Set individual grid stop-loss percentage
cell_sl_percent = -0.05
